language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: BH9ANfOHlbPTJZinqQGJJqTiU7Abwigqjbc/f//29anTsnsyHIw9VO4koNXdFYpCb9V9Y2yLmchMosDTZ7K/HrMXQgRqoG29BspjE2x9idZwR+dk4a5zYDTiEuQEC+oRWHgkS47IoyQsR9ov3iOMtez5Ou2Yy8j//59DhxibeUg=
    - secure: UAjhBozm1b9lslZGOBQsx43JyRFd7Iu8wkqakfCuRvmJuJxoQcwcbrYjK18zR5AaVQcZ1jHc5TV1obSTPoeMcy5a7QepZHvu/WA3bc4eg4lhnDLQ7AvTw9j2g9MOcnE15uzPKkLW8HydJoqtKLJv7PyT1Zb4tbWNcPwXp0EJ5HQ=
  - PHANTOM_JS_BIN_PATH="phantomjs"
